// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PizzaPolis_01.Models
{
    public partial class DetallePedido
    {
        public int IdDetallePedido { get; set; }
        public int Cantidad { get; set; }
        public int SubTotal { get; set; }
        public int IdProducto { get; set; }
        public string Estado { get; set; }
        public int? IdPedido { get; set; }

        public virtual Pedido IdPedidoNavigation { get; set; }
        public virtual Productos IdProductoNavigation { get; set; }
    }
}