// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PizzaPolis_01.Models
{
    public partial class Factura
    {
        public int IdFactura { get; set; }
        public DateTime? FechaHoraEmision { get; set; }
        public string Detalle { get; set; }
        public string EstadodelPedido { get; set; }
        public string Nit { get; set; }
        public int? IdPedido { get; set; }

        public virtual Pedido IdPedidoNavigation { get; set; }
    }
}