// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PizzaPolis_01.Models
{
    public partial class Productos
    {
        public Productos()
        {
            DetallePedido = new HashSet<DetallePedido>();
        }

        public int Id { get; set; }
        public string NombreProd { get; set; }
        public string DetalleProd { get; set; }
        public double PrecioProd { get; set; }

        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
    }
}