// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PizzaPolis_01.Models
{
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Usuario1 { get; set; }
        public string Contraseña { get; set; }
        public int IdRol { get; set; }
        public bool Estado { get; set; }

        public virtual Rol IdRolNavigation { get; set; }
    }
}